Repository DAGsHub/fds, pull requests merged in 2021-07, with the labels that each got.

#70 Show an adding message before showing wizard in DVC add
  fds/services/fds_service.py
Labels: ux

#53 Implement clone command
  README.md
  fds/cli.py
  fds/domain/commands.py
  fds/run.py
  fds/services/base_service.py
  fds/services/dvc_service.py
  fds/services/fds_service.py
  fds/services/git_service.py
  fds/utils.py
  requirements.txt
  tests/it/helpers.py
  tests/it/test_dvc.py
  tests/it/test_fds.py
  tests/it/test_git.py
  tests/test_fds.py
  tests/test_utils.py
Labels: enhancement

#73 Feature to check for latest version before running a command
  fds/__init__.py
  fds/run.py
  requirements.txt
  setup.py
Labels: enhancement, ux

#75 Add ignored files to dvcignore too
  fds/services/dvc_service.py
  tests/it/test_dvc.py
  tests/it/test_fds.py
Labels: bug, ux

#74 Add skip option to `fds add` wizard
  fds/services/dvc_service.py
  fds/services/fds_service.py
  fds/services/git_service.py
  fds/services/types.py
  tests/it/test_dvc.py
  tests/it/test_fds.py
  tests/it/test_git.py
Labels: enhancement, ux

#71 Supporting multiple paths
  fds/cli.py
  fds/services/fds_service.py
  fds/services/git_service.py
  fds/utils.py
Labels: enhancement

#79 Support Multiple Paths for fds add
  fds/cli.py
  fds/run.py
  fds/services/dvc_service.py
  fds/services/fds_service.py
  fds/services/git_service.py
  tests/it/test_dvc.py
  tests/it/test_fds.py
  tests/it/test_git.py
Labels: good first issue, ux

#80 Make `fds push` ask for credentials of user if its not authenticated already
  fds/services/dvc_service.py
  fds/utils.py
  tests/it/helpers.py
Labels: enhancement, ux
