Repository DAGsHub/fds, pull requests merged in 2021-06, with the labels that each got.

#46 Improve UX by showing progress bar while adding large files to DVC and other minor fixes to improve usability
  fds/cli.py
  fds/run.py
  fds/services/base_service.py
  fds/services/dvc_service.py
  fds/services/fds_service.py
  fds/services/git_service.py
  requirements.txt
  tests/test_fds.py
Labels: ux

#50 Add Integration tests and fix a bug with fds add <large file> that doesn't add into dvc
  .github/workflows/test.yml
  fds/services/dvc_service.py
  fds/services/fds_service.py
  fds/services/pretty_print.py
  fds/utils.py
  tests/it/__init__.py
  tests/it/helpers.py
  tests/it/test_dvc.py
  tests/it/test_fds.py
  tests/it/test_git.py
Labels: bug, tests

#55 Support sdf as an alternative command to fds
  setup.py
Labels: ux

#34 Add fds push and save
  .gitignore
  fds/cli.py
  fds/domain/commands.py
  fds/run.py
  fds/services/dvc_service.py
  fds/services/fds_service.py
  fds/services/git_service.py
Labels: enhancement

#61 Got rid of pygit2
  fds/services/git_service.py
  requirements.txt
Labels: bug, chore

#67 Improve fds add performance by checking dvc-ignore when necessary
  fds/services/dvc_service.py
Labels: performance
